### ISSUE TITLE
Project Requirements / Integration Requests

### ISSUE THREAD

**Issue by realRoshanRaj** [AyushPrj/ECE461-Team1-Repository#11]
1. GitHub/NPM url parsed format

- https://github.com/cloudinary/cloudinary_npm -> cloudinary/cloudinary_npm
- https://www.npmjs.com/package/browserify -> browserify

Group into following structs for each url

```go
const(
    GITHUB = 0
    NPM = 1
)

type URL struct {
  site int
  name string
}
```
2. Configure the log file to accept more or less based on the LOG_LEVEL
- these variables can be accessed in the main.go file by using (LOG_LEVEL, LOG_FILE).
- we just have to produce a log file stored in the location named in the ~~environment variable~~
LOG_FILE and using the verbosity level indicated in the ~~environment variable~~ LOG_LEVEL (0
means silent, 1 means informational messages, 2 means debug messages). Default log verbosity
is 0

**Comment by AyushPrj** [comment]
Resolved with branch
