### ISSUE TITLE
Add unit test cases 

### ISSUE THREAD

**Issue by realRoshanRaj** [AyushPrj/ECE461-Team1-Repository#16]
Add unit test cases to each function. Create a dummy response from the api and pass that into the functions to ensure it is giving correct values

**Comment by realRoshanRaj** [comment]
Doing that should produce a high enough code coverage when running

**Comment by realRoshanRaj** [comment]
Main 

1. Invalid File path test
2. Validate ndjson with regex 
3. Validate netscore range (0 to 1)

Metrics 

4-9. Validate that all the 5 metric scores are either -1 or a value between 0 through 1

NPM 
10.  Validate github url given through npm api 

GitHub
11-12. Validate that we calculate the correct the "top contributor contributions" and "total contributions" given dummy struct object.
13. Validate that we compute the correct contribution ratio given "top contributor contributions" and "total contributions"
14. Validate the readme url given the dummy Repo object

Log
15. Test log file output with log_level 0
16. Test log file output with log_level 1
17. Test log file output with log_level 2

**Comment by sklee1216** [comment]
TODO:
1, 11-17
